# Generated by Django 4.1.13 on 2024-06-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='resume/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
